# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - prealloc

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/icarus-itcs/lazycap
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    # Ignore long lines in generated files
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    # Ignore certain issues in main.go
    - path: main\.go
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0
