# GoReleaser configuration for lazycap
# https://goreleaser.com
version: 2

project_name: lazycap

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: lazycap
    main: .
    binary: lazycap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 7
    ignore:
      # Ignore unsupported combinations
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - '^chore\(deps\):'
      - '^chore\(release\):'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: icarus-itcs
    name: lazycap
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew tap icarus-itcs/lazycap https://github.com/icarus-itcs/lazycap
    brew install lazycap
    ```

    **Go Install:**
    ```bash
    go install github.com/icarus-itcs/lazycap@{{ .Tag }}
    ```

    **Manual Download:**
    Download the appropriate archive for your platform below, extract, and move the binary to your PATH.
  footer: |
    ---

    **Full Changelog**: https://github.com/icarus-itcs/lazycap/compare/{{ .PreviousTag }}...{{ .Tag }}
  name_template: "v{{.Version}}"
